### ISSUE TITLE
Not able to pass on the argument for the NMF code

### ISSUE THREAD

**Issue by dguhanus** [raleng/nmf#1]
Dear Ralf Engbers ,
Thank you for the NMF code with all the 4 mechanisms. I am trying to run the code. I am unable to pass on the argument for the NMF code.  I have attached the error of the console. 
Below is the python code written inside a file:

data = "small.jpg"
components = 20
from nmf import NMF
nmf = NMF(data, components)
nmf.factorize(method='mur', distance_type='eu', min_iter='60')

Please let me know how to resolve the issue.
![NMF_Error](https://github.com/raleng/nmf/assets/52912410/115370be-92ab-46ae-aa35-03159662393a)

**Comment by raleng** [comment]
Hi @dguhanus, the code does not handle loading the data for you, it expects a 2-dimensional NumPy array.

One way of doing that would be to use PIL (converting the image to grayscale as well):
```python
import numpy as np
from PIL import Image

img = Image.open('small.jpg').convert('L')
data = np.asarray(img)

nmf = NMF(data, 2)
nmf.factorize(method='mur')
```

---
*Small disclaimer*: this is basically an archive repo and not actively maintained. If you encounter further problems, I am happy to have a look and help as much as I can, but I can not promise extensive support.

**Comment by dguhanus** [comment]
Dear Dr. Ralf Engbers ,
Thank you for your prompt reply and extending your support. After your reply, I am able to execute the MUR and AO-ADMM method. I am encountering a problem when I want to use ADMM.
Below is the code that I am following to invoke ADMM.

`import numpy as np
from PIL import Image

import matplotlib.pyplot as plt
from nmf import NMF

img = Image.open('small.jpg').convert('L')
data = np.asarray(img)
nmf = NMF(data, 50)
nmf.factorize(method='admm', rho=0.2, max_iter=600)
nmf.save_factorization('./results/nmf_exp_admm.npz')
saved_npimag = np.load('./results/nmf_exp_admm.npz')
`
Below is the error that I am encountering due to attribute of rho

`base) dguha@dguha:~/ADMM_Code/nmf$ python admm_sample.py 
/home/dguha/ADMM_Code/nmf/nmf/admm.py:143: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  k = -np.array([np.ones(n - 1), -2 * np.ones(n), np.ones(n - 1)])
[0]: 9854013.478
[1]: 9493382.538
[2]: 9016837.690
[3]: 8484224.720
[4]: 7932726.672
[5]: 7392289.619
[6]: 6881673.294
[7]: 6381249.864
[8]: 5901098.838
[9]: 5426047.522
[10]: 4978864.504
[11]: 4542984.914
[12]: 4117584.656
[13]: 3745558.902
[14]: 3464340.620
[15]: 3389319.959
[16]: 3983838.196
Algorithm converged (2).
WARNING:root:Converged.
Factorization done.
Traceback (most recent call last):
  File "admm_sample.py", line 14, in <module>
    nmf.save_factorization('./results/nmf_exp_admm.npz')
  File "/home/dguha/ADMM_Code/nmf/nmf/nmf.py", line 104, in save_factorization
    save_name += f'_{self.results.experiment.rho}'
AttributeError: 'Experiment' object has no attribute 'rho'
`
Thank you in advance for your support.

**Comment by raleng** [comment]
Hm. I get a different error when trying to reproduce the issue. I might find some time at the end of the week or on the weekend to have a closer look.

**Comment by raleng** [comment]
@dguhanus Feel free to try again. I pushed two changes (#2 & #3) which hopefully fixes your issues.

**Comment by dguhanus** [comment]
Dear Ralf Engbers,
Thank you very much for your update. I have tested, it working fine. But I have another doubt for which I am posting a separate query.

**Comment by raleng** [comment]
Nice, closing this one then. Will checkout the other issue hopefully during this weekend.
