### ISSUE TITLE
Need help for writing Group LASSO ADMM implementation

### ISSUE THREAD

**Issue by dguhanus** [raleng/nmf#5]
Dear Ralf Engbers,
I want to implement Group LASSO in ADMM in Python. The MATLAB code is given here from Stephen Boyd. 
https://web.stanford.edu/~boyd/papers/admm/
and
https://web.stanford.edu/~boyd/papers/admm/group_lasso/group_lasso_feat_split.html 
It will be a great help if you already have it with you. Else, I will write it on my own.

**Comment by raleng** [comment]
Sorry, I never implemented or used LASSO myself, so I won't be able to help you with this one.
